[package]
name = "my_init"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
log4rs = "1.2.0"
chrono = "0.4.22"
serde = "^1.0"
serde_derive = "^1.0"
confy = "^0.5.1"
once_cell = "1.16.0"